"""接入中心 integration_configs

Revision ID: 7b460981f19c
Revises: e4cd267e0ab7
Create Date: 2026-08-10 14:42:23.125117
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7b460981f19c'
down_revision = 'e4cd267e0ab7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('store_identifier', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('requested_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode in ('manual','guided')", name='ck_integration_mode'),
    sa.CheckConstraint("provider in ('shopify','amazon','tiktok_shop')", name='ck_integration_provider'),
    sa.CheckConstraint("status = 'draft'", name='ck_integration_status_draft'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_tenant_id'), 'integration_configs', ['tenant_id'], unique=False)
    op.create_index('ix_integration_tenant_provider_store', 'integration_configs', ['tenant_id', 'provider', 'store_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_tenant_provider_store', table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_tenant_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    # ### end Alembic commands ###
