"""users 改为租户内唯一

Revision ID: e4cd267e0ab7
Revises: 20260809_0001
Create Date: 2026-08-09 23:14:03.320685
"""
from alembic import op
import sqlalchemy as sa


revision = 'e4cd267e0ab7'
down_revision = '20260809_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index('ix_users_tenant_username', 'users', ['tenant_id', 'username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tenant_username', table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
