"""initial schema

Revision ID: 6c8f83ccd7f0
Revises: 
Create Date: 2026-07-21 13:32:29.889485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8f83ccd7f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_title', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'chunk_index', name='uq_doc_chunk_source_idx')
    )
    op.create_index(op.f('ix_doc_chunks_source_id'), 'doc_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_doc_chunks_source_type'), 'doc_chunks', ['source_type'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('school_name', sa.String(length=128), nullable=False),
    sa.Column('school_type', sa.Enum('PUBLIC', 'PRIVATE', name='schooltype'), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('is_establishment', sa.Boolean(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('recruiter_email', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_job_source_external')
    )
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_district'), 'jobs', ['district'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_school_name'), 'jobs', ['school_name'], unique=False)
    op.create_index(op.f('ix_jobs_stage'), 'jobs', ['stage'], unique=False)
    op.create_index(op.f('ix_jobs_subject'), 'jobs', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('structured_content', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('sub_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('districts', sa.JSON(), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('school_types', sa.JSON(), nullable=True),
    sa.Column('salary_floor', sa.Integer(), nullable=True),
    sa.Column('need_establishment', sa.Boolean(), nullable=True),
    sa.Column('llm_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_rules_user_id'), 'sub_rules', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('real_name', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('education', sa.String(length=32), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('cert_no', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_key')
    )
    op.create_index(op.f('ix_user_settings_key'), 'user_settings', ['key'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rule_passed', sa.Boolean(), nullable=False),
    sa.Column('llm_score', sa.Integer(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PUSH', 'PUSHED', 'CONFIRMED', 'IGNORED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['sub_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'job_id', name='uq_match_rule_job')
    )
    op.create_index(op.f('ix_match_results_job_id'), 'match_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_results_rule_id'), 'match_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_match_results_user_id'), 'match_results', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('base_resume_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('tailored_content', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DISCARDED', name='resumeversionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_base_resume_id'), 'resume_versions', ['base_resume_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_user_id'), 'resume_versions', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('resume_version_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_email', sa.String(length=128), nullable=False),
    sa.Column('email_subject', sa.String(length=256), nullable=True),
    sa.Column('resume_url_snapshot', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'BOUNCED', name='applicationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_results.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    这里只 drop_table、不 drop_index：MySQL 会拒绝删除被外键约束依赖的索引
    （错误 1553 Cannot drop index ... needed in a foreign key constraint），
    而 autogenerate 默认会在 drop_table 前逐个 drop_index，回滚必然中途失败。
    删表本身就会连带删掉它的索引，这些调用本就多余。
    删除顺序为建表的反序，以满足外键依赖。
    """
    op.drop_table('applications')
    op.drop_table('resume_versions')
    op.drop_table('match_results')
    op.drop_table('user_settings')
    op.drop_table('user_profiles')
    op.drop_table('templates')
    op.drop_table('sub_rules')
    op.drop_table('resumes')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_table('doc_chunks')
