"""jobs 增加 subjects 多学科字段

一个招聘公告经常同时招多个学科（"语文、数学、英语教师各 1 名"）。
原来的单值 subject 靠在全文里找第一个命中的学科名来填，实测 12 条标为
"语文"的岗位有 11 条其实是多学科招聘——数学老师筛"数学"根本看不到它们。

本迁移只加列，不回填。回填用 scripts/backfill_subjects.py，
因为回填要用到 crawler 的识别逻辑，而迁移不该依赖会随时间变化的应用代码。

Revision ID: adfa33682b3b
Revises: a421c6e81d02
Create Date: 2026-08-12 17:38:37.987936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfa33682b3b'
down_revision: Union[str, Sequence[str], None] = 'a421c6e81d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('subjects', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_subjects'), 'jobs', ['subjects'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚会丢掉多学科信息，但不丢岗位本身，且可用回填脚本重建，
    因此这里允许正常 downgrade。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_subjects'), table_name='jobs')
    op.drop_column('jobs', 'subjects')
    # ### end Alembic commands ###
